name: Pull requests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Load tests
        run: mvn --batch-mode --update-snapshots -Dgroups="load"
        continue-on-error: true